id: A7FF1746B
title: Guru Sādhana of Garab Dorje
type: translation
pechas:
- I66790631
- I4FAB12A4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:16.984009
  last_modified_at: 2023-01-04 12:12:16.984020
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I66790631/1493: '3132'
  I4FAB12A4/E144: '3132'
